thriftrw/thriftrw-node

errors.js, tlist.js, tmap.js, tstruct.js
- fixes lint
- correct Result type in a few places
- object literals are better of spanning lines
cc @kriskowal @leizha
=> Cleanup errors, fix lint

errors.js, index.js, speclist.js, test/index.js, test/speclist.js
Continuing decomposition of #3:
- pivoted api to be `SpecListRW(type :: {name, typeid, rw})`
- implemented typed error
- "100%" test coverage
r @Raynos @kriskowal
=> Add speclist

package.json, test/JavaBeansTest.json, test/thrift-idl.js, test/thrift/AnnotationTest.thrift, test/thrift/BrokenConstants.thrift, test/thrift/ConstantsDemo.thrift, test/thrift/DebugProtoTest.thrift, test/thrift/DenseLinkingTest.thrift, test/thrift/DocTest.thrift, test/thrift/EnumTest.thrift, test/thrift/Include.thrift, test/thrift/JavaBeansTest.thrift, test/thrift/ManyOptionals.thrift, test/thrift/ManyTypedefs.thrift, test/thrift/NameConflictTest.thrift, test/thrift/OptionalRequiredTest.thrift, test/thrift/Recursive.thrift, test/thrift/ReuseObjects.thrift, test/thrift/SmallTest.thrift, test/thrift/StressTest.thrift, test/thrift/ThriftTest.thrift, test/thrift/TypedefTest.thrift, thrift-idl.js, thrift-idl.pegjs
Note that some debt is paid off from the original in Thriftify,
particularly the abbreviated property names, collapsed identifier nodes
(just a string now), and all node types.
r @jcorbin @malandrew 
Next up will be a StructSpec that contains a SpecRW based on its Thrift IDL description.
=> Assimilate Thrift IDL parser

.eslintrc, service.js, spec.js, struct.js, test/service.js, test/service.thrift, test/spec-duplicate-error.thrift, test/spec-reference-error.thrift, test/spec.js, test/spec.thrift, test/struct.js, test/struct.thrift, thrift-idl.pegjs
With only Struct and base types so far, this is the skeleton that orchestrates the conversion of a Thrift IDL AST into a structure with Specs for all the services and structs.
Note the adjustment to the AST so identifiers can carry line and column numbers, to provide insightful reference errors (per @abhinav).
This is intended to be interface compatible with Thriftify so we can just drop it in.
=> Implement Spec and ServiceSpec

service.js, struct.js, test/struct.js
There was an extraneous layer to identifier name AST nodes, in wasted anticipation of needing to grab the location of a field name for error reporting.
=> Fix field name syntax tree

exception.js, test/exception.js, test/exception.thrift
This removes the expectation on the Thrift IDL parser
that all exceptions have type & message annotations.
These annotations do not really make sense in other
languages so it would make it difficult to parse
thrift IDLs from other languages.
r: @kriskowal @abg
=> Remove type annotations from exception

skip.js, struct.js, test/struct-skip.js, test/struct.js
The tests and the implementation were incorrect. The skipper needed to use skipType instead of skipField since the typeid was already read off the wire. skipField continues to exist but only as a vestige of the skip tests. All use in the context of a struct uses skipType.
=> Fix the field skipper and tests

package.json
Upgrading to latest will mean that error has less
dependencies and it will dedupe properly in tchannel-node
r: @kriskowal
=> increase version of error for better dedupe

service.js
The args are constructed by the root thrift model, threading through strict if necessary.
r @malandrew @abhinav
=> Remove unnecessary use of ThriftStruct in service construction

README.md
This PR adds sections detailing:
- how includes work
- include-as is supported experimentally and hidden behind a flag
- how definitions whose identifier is PascalCased will be exposed as a top level property.
=> Include and PascalCase notes added to README

README.md, ast.js, lib/lcp.js, test/idls.js, test/include.js, test/lcp.js, thrift-idl.pegjs, thrift.js
These changes permit a Thrift instance to bootstrap from the file system (using entryPoint and allowFilesystemAccess options), get reduced to an {entryPoint, idls} object via thrift.getSources(), and then get fed back into the Thrift constructor, demonstrating how a service would bootstrap, how it would implement its Meta::thriftIDL endpoint, then how tcurl would bootstrap from the result.
r @raynos @malandrew
=> Implement IDLs interface

lib/lcp.js, test/lcp.js, test/thrift.js, thrift.js
The longest common path algorithm didn't address the case when there was a single file or when a path was not absolute to the file system. This PR fixes that.
=> Fix lcp for single files

service.js, test/include.js
This solves the issue where getType() can't find the _args or _result types for functions inherited through service sub-classing. 
My impression is that there is technical debt that needs to be paid off. More specifically, the _args and _result keys are a legacy of using the original Apache Thrift code as inspiration. 
This PR fixes the issue, but there are some mismatches like the fullName on a function, functions args and function results models not matching the expected name on inheritance. For example, if SuperService extends SubService and SubService has the function getFoo, then the thrift model defining SuperService will have `SuperService::getFoo`, `SuperService::getFoo_args` and `SuperService::getFoo_results` as properties on its `models` property, but the fullNames on the …
=> Expose _args and _results types on parent thrift for extended services

benchmarks/cases.js, boolean.js, enum.js, i64.js, list.js, map-entries.js, map-object.js, package.json, read.js, skip.js, struct.js, test/skip.js, tlist.js, tmap.js, tstruct.js
This isn't quite zero alloc but it's definitely less allocations. I might try and get this branch faster before merging, but right now it passes all tests and does show a performance gain, though it wasn't the 2x improvement I was hoping for.
after, and with bufrw 1.2.0:
```
p25 1.28µs p50 1.35µs p75 1.53µs p90 1.71µs stddev 37.5ns q3-q1/2  372ns 0 thrift
p25 2.10µs p50 2.22µs p75 2.61µs p90 2.77µs stddev 61.0ns q3-q1/2  355ns 0 json
p25 2.56µs p50 2.74µs p75 3.22µs p90 3.35µs stddev 90.5ns q3-q1/2  422ns 1 thrift
p25 3.55µs p50 3.81µs p75 4.50µs p90 4.60µs stddev  131ns q3-q1/2  671ns 1 json
p25 14.2µs p50 14.9µs p75 16.5µs p90 17.8µs stddev  355ns q3-q1/2 1.60µs 10 thrift
p25 13.6µs p50 14.1µs p75 15.5µs p90 17.0µs stddev  280ns q3-q1/2 2.13µs 10 json
p25  132µs p50  138µs p75  144µs …
```
=> Less allocations

errors.js, message.js, service.js, test/index.js, test/message.js, test/thrift.thrift, thrift.js
This adds the argumentsMessageRW and resultMessageRW to the thrift.{Service}.{function} addressable model objects, for all types regardless of whether they are used.
=> Minimum viable Thrift message envelope support

message.js, service.js, test/message.js, thrift.js
This is a bit ugly, but for now, this introduces a couple implicit types in every module for Thrift exceptions, so I can get at the RW object that Thrift generates. Adds tests to round trip exceptions and fail on malformed exception bodies on the wire.
r @abhinav
=> Implement ThriftMessageEnvelopeException RW

list.js, test/list.js, test/list.thrift, typedef.js
see https://github.com/uber/bufrw/pull/59
An aggressive optimization for reuse of prior result object values allows the SeriesRW to mutate a previously rendered array result. This fixes the problem in advance of a fix to BufRW itself and adds a regression test.
r @abhinav @jcorbin 
cc @iproctor
=> Fix list of lists regression

list.js, package.json
This removes the work-around and retains the regression test, which still passes, having updated bufrw with the proper bufix for SeriesRW.
r @jcorbin @Raynos @abhinav
=> Unravel bufrw Series workaround

i16.js, i32.js, i8.js, test/i16.js, test/i32.js, test/i8.js, test/map.js, test/map.thrift
r @prashantv @yarpc/yarpc @yarpc/node
I’ve invited reviewers who do not have context:
This solves the problem that we could not support map<i32, i32> before, because they would by default be stored in an object with string keys. The i32 RW would refuse to coerce the string key to a number. This change solves the problem for all integer types, but not double, boolean, or i64.
i64 remains problematic because I made the decision to coerce strings of hex.
=> Support numeric keys in maps

.istanbul.yml, ast.js, package.json, test/asts.js, test/idls.js, thrift.js, thrift2json.js
Adds a thrift2json tool for converting Thrift IDL to a JSON AST. That JSON AST is accepted as options to construct a Thrift model, so you can bypass the IDL parser.
The Thrift AST may also be useful for caching between tcurls.
r @malandrew @abhinav 
cc @matt-esch
=> Support serialization of a Thrift model through JSON for caching

package.json, thrift-idl.js
Updating thriftrw beyond 3.1.0 caused a serious regression in cpu and memory usage during thrift client creation. I bisected it down to the enabling of the cache option. Reverting the cache option significantly improves performance. The impact of the cache option is to add 10 minutes to our test suite and increase startup time by 10s.
Unless this was added to address a different observed concern, I'm removing the cache option.
=> revert thrift-idl cache option

CHANGELOG.md, README.md, struct.js, test/struct.js, test/thrift.js, thrift.js
We would rather lose structure and allow undefined to be our default value in some circumstances (when serializing to JSON). Add ability to optionally use undefined as the default value.
=> Allow undefined to be default value rather than null

CHANGELOG.md, struct.js, test/default.js, test/default.thrift
Previously null was the default, default value. [This commit](https://github.com/thriftrw/thriftrw-node/commit/34a8b1b80a46482cbbc3777c7a635d57db59d59b) allowed the user to specify undefined as a default value as well, but it did not change the creation of the constructor. In order to allow undefined or null to be used as the default value, always use the default value if a value for the field is not provided in the options.
=> Fix constructor for undefined default values

.travis.yml, test/i64.js, thrift.js
Node 8 changed the behavior of Date.parse.
The default timezone changed.
This change now makes the UTC timezone explicit.
=> Fix i64 Date test

test/thrift-idl.js, test/thrift.js, thrift-idl.js, thrift.js
The "XYZ_args not found" error can be caused by an invalid service name or a method name that is not found within the service. The error should help the user understand this issue.
=> Improved _args not found error to be more helpful.

package-lock.json, package.json, test/thrift.js, thrift.js
This change fixes lint in old (0.10) and new (12) versions of Node.js.
=> Revert eslint to ^2

i16.js, i32.js, i64.js, i8.js, message.js, skip.js, test/i32.js, test/i64.js, test/i8.js, test/skip.js
Subsuming and following up to #156, this removes the use of the long-past-deprecated field bounds assertion argument and preempts it with explicit boundary checks and errors.
=> No buffer asserts

benchmarks/cases.js, binary.js, i64.js, test/enum.js, test/i64.js, test/i8.js, test/message.js, test/set.js, test/skip.js, test/struct-skip.js, test/struct.js, test/thrift.js, test/tmap.js, test/tstruct.js, test/unrecognized-exception.js
Node.js deprecated the overloaded Buffer constructor in favor of Buffer.from and Buffer.alloc.  This change introduces a convention that allows ThriftRW to continue using old patterns when run under old versions of Node.js, while avoiding the deprecation warnings on modern runtimes.
Avoid global Buffer lint directive. This is consistently elsewhere addressed by expressly importing the shimmable buffer module.
=> Address Node.js Buffer constructor deprecations

CHANGELOG.md, thrift.js
This change inlines the _init method into the Thrift constructor and pivots the async vs sync behavior from Thrift.load into the Thrift constructor, using a `callback` option which also replaces the signal `asyncReadFile` used previously to switch off the synchronous constructor behaviors.  V8 infers the final hidden classe produced by a constructor function from the properties created within the constructor function so inlining bypasses the creation of intermediate hidden classes.
Previous changes inferred that this project uses underscore prefixes for private methods, based on the precedent of compile/_compile.  This change corrects that misunderstanding by renaming some methods.
=> Polish async loader
