thriftrw/thriftrw-node

boolean.js
=> Add BooleanRW

.istanbul.yml, package.json, test/index.js, test/tlist.js, test/tmap.js, test/tstruct.js
=> Reboot tests

test/tlist.js, tlist.js
=> "100%" coverage for TList

test/tmap.js, tmap.js
=> "100%" test coverage for TMap

test/tstruct.js, tstruct.js
=> "100%" coverage for TStruct

.istanbul.yml
=> Keep It 100%

skip.js, test/index.js, test/skip.js, tlist.js, tmap.js
=> Skip reader for arbitrary thrift binary protocol

errors.js, struct.js, test/index.js, test/struct.js, thrift-idl.pegjs
=> Implement StructSpec

service.js, struct.js, test/service.thrift, test/spec-reference-error.thrift, test/spec.thrift, test/struct.js, test/struct.thrift, thrift-idl.pegjs
r @malandrew @abhinav @jcorbin @leizha
=> Enforce ordinal field identifiers

service.js, spec.js, struct.js, test/service.js
=> Expose service object on spec

exception.js, spec.js, test/exception.js, test/exception.thrift
=> Implement ExceptionSpec

thrift-idl.pegjs
=> Thread annotations through map, set, and list IDL syntax

binary.js, boolean.js, byte.js, double.js, i16.js, i32.js, i64.js, list.js, string.js, struct.js, test/list.js, void.js
=> Name all the specs

service.js, spec.js, struct.js, test/default.js, test/default.thrift, test/index.js, test/struct.js, thrift-idl.pegjs
=> Implement default values

MIGRATION.md, index.js, spec.js, struct.js, test/spec.js, test/spec.thrift
And migration doc
r @raynos @leizha @jcorbin @malandrew
=> Interface parity with Thriftify

enum.js, errors.js, spec.js, test/enum-collision.thrift, test/enum-overflow.thrift, test/enum.js, test/enum.thrift, test/index.js, thrift-idl.pegjs
=> Implement EnumSpec

spec.js, struct.js, test/typedef.js, test/typedef.thrift, thrift-idl.pegjs, typedef.js
=> Implement Typedef

spec.js, test/index.js, test/recursion.js, test/recursion.thrift
=> Test recursion

boolean.js, i64.js, list.js, map.js, skip.js, specmap-entries.js, specmap-obj.js, struct.js, tlist.js, tmap.js, tstruct.js
=> Normalize usage of errors and results

ast.js, enum.js, service.js, thrift-idl.js, thrift-idl.pegjs
=> Expose (and use) syntax tree outside the parser

struct.js, test/map.js, test/union.js, thrift.js, union.js
r @malandrew @Raynos @ShanniLi @abhinav
=> Implement Union

errors.js, struct.js, test/struct.js
=> Validate required fields of structs

service.js, test/service.js, test/service.thrift
=> Fix logic error for success result type

set.js, test/set.js
Fixes a bug identified by @Willyham
=> Fix set typeid

i64.js, test/i64.js
This should address https://github.com/uber/tcurl/issues/54
=> Enable coercion to i64 via various JSON expressible forms

i64.js, package.json, test/i64.js, test/i64.thrift, test/thrift-test.js
=> Add support for Long representation of i64

exception.js, index.js, read.js, skip.js, struct.js, test/unrecognized-exception-v1.thrift, test/unrecognized-exception-v2.thrift, test/unrecognized-exception.js, unrecognized-exception.js
This PR adds support for ThriftUnrecognizedException so we can read the values off exceptions from the FUTURE!
This is a work in progress. Feedback appreciated.
@kriskowal
=> ThriftUnrecognizedException support

set.js, struct.js, test/set.js
=> Tolerate lists in place of sets on the wire

ast.js, service.js, test/service-duplicate-function-error.thrift, test/service.js, test/service.thrift, thrift-idl.pegjs, thrift.js
This is the Service extends from BaseService feature from #85 pulled out as a separate pull request.
=> Service extends from BaseService

.istanbul.yml, benchmarks/array-of-coordinates.js, benchmarks/benchmark.thrift, benchmarks/cases.js, benchmarks/lib/benchmark.js, benchmarks/lib/humanize.js, benchmarks/lib/longtime.js, benchmarks/lib/x100.js, benchmarks/objects.js, package.json
This is a preliminary benchmark that compares JSON and Thrift operations for arrays of coordinates, with various orders of magnitude. In short, ThriftRW can read substantially more quickly than JSON, and JSON is faster for writing.
The next benchmark will measure small structs.
```
p50  287ns p75  377ns p90  553ns stdev  128ns 0 json read
p50 17.4µs p75 22.5µs p90 29.4µs stdev 14.8µs 0 thrift read
p50  504ns p75  627ns p90  783ns stdev  237ns 0 json write pojo
p50  469ns p75  540ns p90  821ns stdev  288ns 0 thrift write pojo
p50  147ns p75  175ns p90  264ns stdev  213ns 0 thrift measure pojo
p50  604ns p75  718ns p90 1.11µs stdev  629ns 0 json write model
p50  461ns p75  533ns p90  723ns stdev  196ns 0 thrift write model
p50  146ns p75  169ns p90  235ns stdev 82.7ns 0 thrift measure model …
```
=> Implement preliminary benchmark

test/thrift.js, test/thrift/MultiService.thrift, thrift.js
=> Add ability to get service endpoint names

README.md
@kriskowal
Noticed when I copy-pasted this.
=> Fix derp in readme

README.md, package.json
Pending: Travis, Coveralls, Testlings. They'll need to be migrated to the new repos first.
=> Update links to the repo.

i64.js, test/i64.js
@kriskowal 
Fixes https://github.com/uber/thriftrw-node/issues/110 if the proposal is accepted.
=> Accept array/buffer as DateRW input

struct.js, test/struct.js
=> Methods to convert structs to and from buffers

rw.js, struct.js
=> Factor out RW base

README.md
=> Document message envelopes

README.md, struct.js, test/struct.js, thrift.js
=> Add flag to allow optional arguments

test/thrift/GoTag.thrift, thrift-idl.js, thrift-idl.pegjs
=> Fix escapes in IDL strings
